#!/usr/bin/env python

import argparse
from pyp2rpmlib import Convertor

parser = argparse.ArgumentParser(description = 'Convert PyPI package to RPM specfile.')
parser.add_argument('-p',
                    required = True,
                    help = 'Name of the package on PyPI',
                    metavar = 'PYPI_NAME'
                   )

ns = parser.parse_args()
# TODO: add arguments and pass them to Convertor
convertor = Convertor(name = ns.__dict__['p'], source_from = 'pypi', metadata_from = 'pypi')
print convertor.convert()
