name: Run tox with various Python versions

on:
  push:
  pull_request:

jobs:
  tox_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Tox tests
        uses: fedora-python/tox-github-action@master
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: python2-setuptools python3-wheel ${{ matrix.dnf_install }}

    strategy:
      fail-fast: false
      matrix:
        tox_env: [py36, py37, py38, py39, py310]
        include:
          # Python 3.10 needs to compile cffi
          - tox_env: py310
            dnf_install: libffi-devel
